spring:
  application:
    name: carparkapi
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/carpark_db}
    username: ${SPRING_DATASOURCE_USERNAME:carpark_user}
    password: ${SPRING_DATASOURCE_PASSWORD:carpark_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
logging:
  level:
    com.wego: DEBUG
    org.springframework.web: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/carpark.log

app:
  carpark:
    csv:
      file-path: data/hdb-carpark-information.csv
    api:
      url: https://api.data.gov.sg/v1/transport/carpark-availability
      timeout: 10000
